my_app/catalog/views.py
import os
from werkzeug import secure_filename
from flask import request, jsonify, Blueprint, render_template, \
    flash, redirect, url_for
from sqlalchemy.orm.util import join
from my_app import db, redis
from my_app.catalog.models import Product, Category
from .decorators import template_or_json
from .forms import ProductForm, CategoryForm
from .. import app
from my_app import ALLOWED_EXTENSTIONS

catalog = Blueprint('catalog', __name__)


def allowed_file(filename):
    return '.' in filename and \
        filename.lower().rsplit('.', 1)[1] in ALLOWED_EXTENSTIONS


@catalog.route('/')
@catalog.route('/home')
@template_or_json('home.html')
def home():
    products = Product.query.all()
    return {'count': len(products)}


@catalog.route('/product/<id>')
def product(id):
    product = Product.query.get_or_404(id)
    # product_key = 'product-%s' % product.id
    # redis.set(product_key, product.name)
    # redis.expire(product_key, 30)
    return render_template('product.html', product=product)


@catalog.route('/recent-products')
def recent_products():
    keys_alive = redis.keys('product-*')
    products = [redis.get(k) for k in keys_alive]
    return jsonify({'products': products})


@catalog.route('/products')
@catalog.route('/products/<int:page>')
def products(page=1):
    # products = Product.query.paginate(page, 2).items
    # res = {}
    # for product in products:
    #     res[product.id] = {
    #         'name': product.name,
    #         'price': str(product.price),
    #         'category': product.category.name
    #     }
    # return jsonify(res)
    products = Product.query.paginate(page, 2)
    return render_template('products.html', products=products)


@catalog.route('/product-create', methods=['GET', 'POST'])
def create_product():
    form = ProductForm(request.form)

    if form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        category = Category.query.get_or_404(
            form.category.data
        )
        image = request.files['image']
        filename = ''
        if image and allowed_file(image.filename):
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        product = Product(name, price, category, filename)
        db.session.add(product)
        db.session.commit()
        flash('The product %s has been created' % name, 'success')
        return redirect(url_for('catalog.product', id=product.id))

    if form.errors:
        flash(form.errors, 'danger')

    return render_template('product-create.html', form=form)


@catalog.route('/category-create', methods=['GET', 'POST'])
def create_category():
    form = CategoryForm(request.form)

    if form.validate_on_submit():
        name = form.name.data
        category = Category(name)
        db.session.add(category)
        db.session.commit()
        flash('The category %s has been created' % name,
              'success')
        return redirect(url_for('catalog.create_category',
                                id=category.id))

    if form.errors:
        flash(form.errors, 'danger')

    return render_template('category-create.html', form=form)


@catalog.route('/category/<int:id>')
def category(id):
    category = Category.query.get_or_404(id)
    return render_template('category.html', category=category)


@catalog.route('/categories')
def categories():
    categories = Category.query.all()
    # res = {}
    # for category in categories:
    #     res[category.id] = {
    #         'name': category.name
    #     }
    #     res[category.id]['products'] = {}
    #     for product in category.products:
    #         # res[category.id]['products'].setdefault(product.id,
    #         #                                         {'name': product.name,
    #         #                                          'price': product.price})
    #         res[category.id]['products'][product.id] = {'name': product.name,
    #                                                     'price': product.price}
    # return jsonify(res)
    return render_template('categories.html', categories=categories)


@catalog.route('/product-search')
@catalog.route('/product-search/<int:page>')
def product_search(page=1):
    name = request.args.get('name')
    price = request.args.get('price')
    company = request.args.get('company')
    category = request.args.get('category')
    products = Product.query
    if name:
        products = products.filter(Product.name.like('%' + name +'%'))
    if price:
        products = products.filter(Product.price == price)
    if company:
        products = products.filter(Product.company.like('%' +company + '%'))
    if category:
        products = products.select_from(join(Product,
             Category)).filter(
                Category.name.like('%' + category + '%'))
    return render_template(
            'products.html', products=products.paginate(page, 10)
    )

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    <title>Flask Framework Cookbook</title>
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('catalog.home') }}">Flask Cookbook</a>
            </div>
        </div>
    </div>
    <div class="container">
        <br/>
        <div>
            {% for category, message in get_flashed_messages(with_categories=true) %}
                <div class="alert alert-{{category}} alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% block container %}{% endblock %}
    </div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ url_for('static', filename='js/jquery-2.1.4.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script>
        var csrfToken = $('meta[name="csrf-token"]').attr('content');

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
        }
    })
    </script>
    {% block scripts %}{% endblock %}
</body>
</html>

my_app/templates/categories.html
{% extends 'home.html' %}


{% block container %}
<div class="top-pad">
    {% for category in categories %}
    <a href="{{ url_for('catalog.category', id=category.id) }}">
        <h2>{{ category.name }}</h2>
    </a>
    {% endfor %}
</div>
{% endblock %}

my_app/templates/category-create.html
{% extends 'home.html' %}


{% block container %}
<div class="top-pad">
    <form method="POST" action="{{ url_for('catalog.create_category') }}" role="form">
        {{ form.csrf_token }}
    <div class="form-group">
        {{ form.name.label }}: {{ form.name() }}
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>
{% endblock %}

my_app/templates/category.html
{% extends 'home.html' %}


{% block container %}
<div class="top-pad">
    <h2>{{ category.name }}</h2>
    <div class="well">
        {% for product in category.products %}
        <h3>
            <a href="{{ url_for('catalog.product', id=product.id) }}">{{
                    product.name }}</a>
            <small>$ {{ product.price }}</small>
        </h3>
        {% endfor %}
    </div>
</div>
{% endblock %}

my_app/templates/home.html
{% extends 'base.html' %}


{% block container %}
    <h1>Welcome to the Catalog Home</h1>
    <a href="{{ url_for('catalog.products') }}" id="catalog_link">
        Click here to see the catalog
    </a>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $.getJSON("/home", function(data){
                $('#catalog_link').append('<span class="badge">' + data.count
                 + '</span>');
            });
        });
    </script>
{% endblock %}

my_app/templates/product-create.html
{% extends 'home.html' %}


{% block container %}
<div class="top-pad">
    <form class="form-horizontal" method="POST" action="{{ url_for('catalog.create_product') }}"
          role="form" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="form-group">
{#            <label for="name" class="col-sm-2 control-label">Name</label>#}
{#            <div class="col-sm-10">#}
{#                <input type="text" class="form-control" id="name" name="name">#}
{#            </div>#}
            {{ form.name.label }}:{{ form.name(required='') }}
        </div>
        <div class="form-group">
{#            <label for="price" class="col-sm-2 control-label">Price</label>#}
{#            <div class="col-sm-10">#}
{#                <input type="number" class="form-control" id="price" name="price">#}
{#            </div>#}
            {{ form.price.label }}:{{ form.price(required='') }}
        </div>
        <div class="form-group">
{#            <label for="category" class="col-sm-2 control-label">Category</label>#}
{#            <div class="col-sm-10">#}
{#                <input type="text" class="form-control" id="category" name="category">#}
{#            </div>#}
            {{ form.category.label }}:{{ form.category(required='') }}
        </div>
        <div class="form-group">
            {{ form.image.label }}:{{ form.image(style='display:inline;') }}
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>
{% endblock %}

my_app/templates/product.html
{% extends 'home.html' %}


{% block container %}
<div class="top-pad">
    <img src="{{ url_for('static', filename='uploads/' + product.image_path) }}" style="height: 450px;width: 750px">
    <h1>{{ product.name }}<small> {{ product.category.name
            }}</small></h1>
{#    <h4>{{ product.company }}</h4>#}
    <h3>{{ product.price }}</h3>
</div>
{% endblock %}

my_app/templates/products.html
{% extends 'home.html' %}


{% block container %}
<div class="top-pad">
    {% for product in products.items %}
    <div class="well">
        <h2>
            <a href="{{ url_for('catalog.product', id=product.id)
                    }}">{{ product.name }}</a>
            <small>$ {{ product.price }}</small>
        </h2>
    </div>
    {% endfor %}
{% if products.has_prev %}
    <a href="{{ url_for('catalog.products',
    page=products.prev_num) }}">
        {{"<< Previous Page"}}
    </a>
{% else %}
    {{"<< Previous Page"}}
{% endif %} |
{% if products.has_next %}
    <a href="{{ url_for('catalog.products',
    page=products.next_num) }}">
        {{"Next page >>"}}
    </a>
{% else %}
    {{"Next page >>"}}
{% endif %}
</div>
{% endblock %}